// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.36.0
// source: proto/drug.proto

package drugpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DrugService_GetDrug_FullMethodName     = "/drug.DrugService/GetDrug"
	DrugService_SearchDrugs_FullMethodName = "/drug.DrugService/SearchDrugs"
	DrugService_CreateDrug_FullMethodName  = "/drug.DrugService/CreateDrug"
	DrugService_UpdateDrug_FullMethodName  = "/drug.DrugService/UpdateDrug"
	DrugService_PatchDrug_FullMethodName   = "/drug.DrugService/PatchDrug"
	DrugService_DeleteDrug_FullMethodName  = "/drug.DrugService/DeleteDrug"
	DrugService_SyncFromFDA_FullMethodName = "/drug.DrugService/SyncFromFDA"
)

// DrugServiceClient is the client API for DrugService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ---------- The service: what methods exist ----------
type DrugServiceClient interface {
	// ---- Read ----
	// Unary: ask for one drug, get one drug
	GetDrug(ctx context.Context, in *GetDrugRequest, opts ...grpc.CallOption) (*Drug, error)
	// Server-streaming: ask once, results flow in one by one
	SearchDrugs(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Drug], error)
	// ---- Write ----
	// Add a brand new drug
	CreateDrug(ctx context.Context, in *CreateDrugRequest, opts ...grpc.CallOption) (*Drug, error)
	// Replace every field of an existing drug
	UpdateDrug(ctx context.Context, in *UpdateDrugRequest, opts ...grpc.CallOption) (*Drug, error)
	// Change only the fields that were sent
	PatchDrug(ctx context.Context, in *PatchDrugRequest, opts ...grpc.CallOption) (*Drug, error)
	// Remove a drug
	DeleteDrug(ctx context.Context, in *DeleteDrugRequest, opts ...grpc.CallOption) (*DeleteDrugResponse, error)
	// ---- Admin ----
	// Unary: pull fresh data from openFDA into our database
	SyncFromFDA(ctx context.Context, in *SyncRequest, opts ...grpc.CallOption) (*SyncResponse, error)
}

type drugServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDrugServiceClient(cc grpc.ClientConnInterface) DrugServiceClient {
	return &drugServiceClient{cc}
}

func (c *drugServiceClient) GetDrug(ctx context.Context, in *GetDrugRequest, opts ...grpc.CallOption) (*Drug, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Drug)
	err := c.cc.Invoke(ctx, DrugService_GetDrug_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *drugServiceClient) SearchDrugs(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Drug], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DrugService_ServiceDesc.Streams[0], DrugService_SearchDrugs_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SearchRequest, Drug]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DrugService_SearchDrugsClient = grpc.ServerStreamingClient[Drug]

func (c *drugServiceClient) CreateDrug(ctx context.Context, in *CreateDrugRequest, opts ...grpc.CallOption) (*Drug, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Drug)
	err := c.cc.Invoke(ctx, DrugService_CreateDrug_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *drugServiceClient) UpdateDrug(ctx context.Context, in *UpdateDrugRequest, opts ...grpc.CallOption) (*Drug, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Drug)
	err := c.cc.Invoke(ctx, DrugService_UpdateDrug_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *drugServiceClient) PatchDrug(ctx context.Context, in *PatchDrugRequest, opts ...grpc.CallOption) (*Drug, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Drug)
	err := c.cc.Invoke(ctx, DrugService_PatchDrug_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *drugServiceClient) DeleteDrug(ctx context.Context, in *DeleteDrugRequest, opts ...grpc.CallOption) (*DeleteDrugResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteDrugResponse)
	err := c.cc.Invoke(ctx, DrugService_DeleteDrug_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *drugServiceClient) SyncFromFDA(ctx context.Context, in *SyncRequest, opts ...grpc.CallOption) (*SyncResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SyncResponse)
	err := c.cc.Invoke(ctx, DrugService_SyncFromFDA_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DrugServiceServer is the server API for DrugService service.
// All implementations must embed UnimplementedDrugServiceServer
// for forward compatibility.
//
// ---------- The service: what methods exist ----------
type DrugServiceServer interface {
	// ---- Read ----
	// Unary: ask for one drug, get one drug
	GetDrug(context.Context, *GetDrugRequest) (*Drug, error)
	// Server-streaming: ask once, results flow in one by one
	SearchDrugs(*SearchRequest, grpc.ServerStreamingServer[Drug]) error
	// ---- Write ----
	// Add a brand new drug
	CreateDrug(context.Context, *CreateDrugRequest) (*Drug, error)
	// Replace every field of an existing drug
	UpdateDrug(context.Context, *UpdateDrugRequest) (*Drug, error)
	// Change only the fields that were sent
	PatchDrug(context.Context, *PatchDrugRequest) (*Drug, error)
	// Remove a drug
	DeleteDrug(context.Context, *DeleteDrugRequest) (*DeleteDrugResponse, error)
	// ---- Admin ----
	// Unary: pull fresh data from openFDA into our database
	SyncFromFDA(context.Context, *SyncRequest) (*SyncResponse, error)
	mustEmbedUnimplementedDrugServiceServer()
}

// UnimplementedDrugServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDrugServiceServer struct{}

func (UnimplementedDrugServiceServer) GetDrug(context.Context, *GetDrugRequest) (*Drug, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDrug not implemented")
}
func (UnimplementedDrugServiceServer) SearchDrugs(*SearchRequest, grpc.ServerStreamingServer[Drug]) error {
	return status.Error(codes.Unimplemented, "method SearchDrugs not implemented")
}
func (UnimplementedDrugServiceServer) CreateDrug(context.Context, *CreateDrugRequest) (*Drug, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateDrug not implemented")
}
func (UnimplementedDrugServiceServer) UpdateDrug(context.Context, *UpdateDrugRequest) (*Drug, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateDrug not implemented")
}
func (UnimplementedDrugServiceServer) PatchDrug(context.Context, *PatchDrugRequest) (*Drug, error) {
	return nil, status.Error(codes.Unimplemented, "method PatchDrug not implemented")
}
func (UnimplementedDrugServiceServer) DeleteDrug(context.Context, *DeleteDrugRequest) (*DeleteDrugResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteDrug not implemented")
}
func (UnimplementedDrugServiceServer) SyncFromFDA(context.Context, *SyncRequest) (*SyncResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SyncFromFDA not implemented")
}
func (UnimplementedDrugServiceServer) mustEmbedUnimplementedDrugServiceServer() {}
func (UnimplementedDrugServiceServer) testEmbeddedByValue()                     {}

// UnsafeDrugServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DrugServiceServer will
// result in compilation errors.
type UnsafeDrugServiceServer interface {
	mustEmbedUnimplementedDrugServiceServer()
}

func RegisterDrugServiceServer(s grpc.ServiceRegistrar, srv DrugServiceServer) {
	// If the following call panics, it indicates UnimplementedDrugServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DrugService_ServiceDesc, srv)
}

func _DrugService_GetDrug_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDrugRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DrugServiceServer).GetDrug(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DrugService_GetDrug_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DrugServiceServer).GetDrug(ctx, req.(*GetDrugRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DrugService_SearchDrugs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SearchRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DrugServiceServer).SearchDrugs(m, &grpc.GenericServerStream[SearchRequest, Drug]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DrugService_SearchDrugsServer = grpc.ServerStreamingServer[Drug]

func _DrugService_CreateDrug_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateDrugRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DrugServiceServer).CreateDrug(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DrugService_CreateDrug_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DrugServiceServer).CreateDrug(ctx, req.(*CreateDrugRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DrugService_UpdateDrug_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateDrugRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DrugServiceServer).UpdateDrug(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DrugService_UpdateDrug_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DrugServiceServer).UpdateDrug(ctx, req.(*UpdateDrugRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DrugService_PatchDrug_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PatchDrugRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DrugServiceServer).PatchDrug(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DrugService_PatchDrug_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DrugServiceServer).PatchDrug(ctx, req.(*PatchDrugRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DrugService_DeleteDrug_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteDrugRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DrugServiceServer).DeleteDrug(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DrugService_DeleteDrug_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DrugServiceServer).DeleteDrug(ctx, req.(*DeleteDrugRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DrugService_SyncFromFDA_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SyncRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DrugServiceServer).SyncFromFDA(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DrugService_SyncFromFDA_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DrugServiceServer).SyncFromFDA(ctx, req.(*SyncRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DrugService_ServiceDesc is the grpc.ServiceDesc for DrugService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DrugService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "drug.DrugService",
	HandlerType: (*DrugServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetDrug",
			Handler:    _DrugService_GetDrug_Handler,
		},
		{
			MethodName: "CreateDrug",
			Handler:    _DrugService_CreateDrug_Handler,
		},
		{
			MethodName: "UpdateDrug",
			Handler:    _DrugService_UpdateDrug_Handler,
		},
		{
			MethodName: "PatchDrug",
			Handler:    _DrugService_PatchDrug_Handler,
		},
		{
			MethodName: "DeleteDrug",
			Handler:    _DrugService_DeleteDrug_Handler,
		},
		{
			MethodName: "SyncFromFDA",
			Handler:    _DrugService_SyncFromFDA_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SearchDrugs",
			Handler:       _DrugService_SearchDrugs_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/drug.proto",
}
