// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.0
// source: proto/drug.proto

package drugpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Drug struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	BrandName     string                 `protobuf:"bytes,2,opt,name=brand_name,json=brandName,proto3" json:"brand_name,omitempty"`
	GenericName   string                 `protobuf:"bytes,3,opt,name=generic_name,json=genericName,proto3" json:"generic_name,omitempty"`
	Manufacturer  string                 `protobuf:"bytes,4,opt,name=manufacturer,proto3" json:"manufacturer,omitempty"`
	ProductNdc    string                 `protobuf:"bytes,5,opt,name=product_ndc,json=productNdc,proto3" json:"product_ndc,omitempty"`
	ProductType   string                 `protobuf:"bytes,6,opt,name=product_type,json=productType,proto3" json:"product_type,omitempty"`
	Route         string                 `protobuf:"bytes,7,opt,name=route,proto3" json:"route,omitempty"`
	SubstanceName string                 `protobuf:"bytes,8,opt,name=substance_name,json=substanceName,proto3" json:"substance_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Drug) Reset() {
	*x = Drug{}
	mi := &file_proto_drug_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Drug) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Drug) ProtoMessage() {}

func (x *Drug) ProtoReflect() protoreflect.Message {
	mi := &file_proto_drug_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Drug.ProtoReflect.Descriptor instead.
func (*Drug) Descriptor() ([]byte, []int) {
	return file_proto_drug_proto_rawDescGZIP(), []int{0}
}

func (x *Drug) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Drug) GetBrandName() string {
	if x != nil {
		return x.BrandName
	}
	return ""
}

func (x *Drug) GetGenericName() string {
	if x != nil {
		return x.GenericName
	}
	return ""
}

func (x *Drug) GetManufacturer() string {
	if x != nil {
		return x.Manufacturer
	}
	return ""
}

func (x *Drug) GetProductNdc() string {
	if x != nil {
		return x.ProductNdc
	}
	return ""
}

func (x *Drug) GetProductType() string {
	if x != nil {
		return x.ProductType
	}
	return ""
}

func (x *Drug) GetRoute() string {
	if x != nil {
		return x.Route
	}
	return ""
}

func (x *Drug) GetSubstanceName() string {
	if x != nil {
		return x.SubstanceName
	}
	return ""
}

type GetDrugRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // has one field
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDrugRequest) Reset() {
	*x = GetDrugRequest{}
	mi := &file_proto_drug_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDrugRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDrugRequest) ProtoMessage() {}

func (x *GetDrugRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_drug_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDrugRequest.ProtoReflect.Descriptor instead.
func (*GetDrugRequest) Descriptor() ([]byte, []int) {
	return file_proto_drug_proto_rawDescGZIP(), []int{1}
}

func (x *GetDrugRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type SearchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"` // has two fields
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchRequest) Reset() {
	*x = SearchRequest{}
	mi := &file_proto_drug_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRequest) ProtoMessage() {}

func (x *SearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_drug_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRequest.ProtoReflect.Descriptor instead.
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return file_proto_drug_proto_rawDescGZIP(), []int{2}
}

func (x *SearchRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type SyncRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         int32                  `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"` // how many records to pull from openFDA
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncRequest) Reset() {
	*x = SyncRequest{}
	mi := &file_proto_drug_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncRequest) ProtoMessage() {}

func (x *SyncRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_drug_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncRequest.ProtoReflect.Descriptor instead.
func (*SyncRequest) Descriptor() ([]byte, []int) {
	return file_proto_drug_proto_rawDescGZIP(), []int{3}
}

func (x *SyncRequest) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type SyncResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fetched       int32                  `protobuf:"varint,1,opt,name=fetched,proto3" json:"fetched,omitempty"` // how many came back from openFDA
	Saved         int32                  `protobuf:"varint,2,opt,name=saved,proto3" json:"saved,omitempty"`     // how many we actually stored
	Skipped       int32                  `protobuf:"varint,3,opt,name=skipped,proto3" json:"skipped,omitempty"` // how many we rejected as unusable
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncResponse) Reset() {
	*x = SyncResponse{}
	mi := &file_proto_drug_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncResponse) ProtoMessage() {}

func (x *SyncResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_drug_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncResponse.ProtoReflect.Descriptor instead.
func (*SyncResponse) Descriptor() ([]byte, []int) {
	return file_proto_drug_proto_rawDescGZIP(), []int{4}
}

func (x *SyncResponse) GetFetched() int32 {
	if x != nil {
		return x.Fetched
	}
	return 0
}

func (x *SyncResponse) GetSaved() int32 {
	if x != nil {
		return x.Saved
	}
	return 0
}

func (x *SyncResponse) GetSkipped() int32 {
	if x != nil {
		return x.Skipped
	}
	return 0
}

var File_proto_drug_proto protoreflect.FileDescriptor

const file_proto_drug_proto_rawDesc = "" +
	"\n" +
	"\x10proto/drug.proto\x12\x04drug\"\xfd\x01\n" +
	"\x04Drug\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"brand_name\x18\x02 \x01(\tR\tbrandName\x12!\n" +
	"\fgeneric_name\x18\x03 \x01(\tR\vgenericName\x12\"\n" +
	"\fmanufacturer\x18\x04 \x01(\tR\fmanufacturer\x12\x1f\n" +
	"\vproduct_ndc\x18\x05 \x01(\tR\n" +
	"productNdc\x12!\n" +
	"\fproduct_type\x18\x06 \x01(\tR\vproductType\x12\x14\n" +
	"\x05route\x18\a \x01(\tR\x05route\x12%\n" +
	"\x0esubstance_name\x18\b \x01(\tR\rsubstanceName\" \n" +
	"\x0eGetDrugRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\";\n" +
	"\rSearchRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"#\n" +
	"\vSyncRequest\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x05R\x05count\"X\n" +
	"\fSyncResponse\x12\x18\n" +
	"\afetched\x18\x01 \x01(\x05R\afetched\x12\x14\n" +
	"\x05saved\x18\x02 \x01(\x05R\x05saved\x12\x18\n" +
	"\askipped\x18\x03 \x01(\x05R\askipped2\xa2\x01\n" +
	"\vDrugService\x12+\n" +
	"\aGetDrug\x12\x14.drug.GetDrugRequest\x1a\n" +
	".drug.Drug\x120\n" +
	"\vSearchDrugs\x12\x13.drug.SearchRequest\x1a\n" +
	".drug.Drug0\x01\x124\n" +
	"\vSyncFromFDA\x12\x11.drug.SyncRequest\x1a\x12.drug.SyncResponseB\x17Z\x15drugsync/proto;drugpbb\x06proto3"

var (
	file_proto_drug_proto_rawDescOnce sync.Once
	file_proto_drug_proto_rawDescData []byte
)

func file_proto_drug_proto_rawDescGZIP() []byte {
	file_proto_drug_proto_rawDescOnce.Do(func() {
		file_proto_drug_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_drug_proto_rawDesc), len(file_proto_drug_proto_rawDesc)))
	})
	return file_proto_drug_proto_rawDescData
}

var file_proto_drug_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_drug_proto_goTypes = []any{
	(*Drug)(nil),           // 0: drug.Drug
	(*GetDrugRequest)(nil), // 1: drug.GetDrugRequest
	(*SearchRequest)(nil),  // 2: drug.SearchRequest
	(*SyncRequest)(nil),    // 3: drug.SyncRequest
	(*SyncResponse)(nil),   // 4: drug.SyncResponse
}
var file_proto_drug_proto_depIdxs = []int32{
	1, // 0: drug.DrugService.GetDrug:input_type -> drug.GetDrugRequest
	2, // 1: drug.DrugService.SearchDrugs:input_type -> drug.SearchRequest
	3, // 2: drug.DrugService.SyncFromFDA:input_type -> drug.SyncRequest
	0, // 3: drug.DrugService.GetDrug:output_type -> drug.Drug
	0, // 4: drug.DrugService.SearchDrugs:output_type -> drug.Drug
	4, // 5: drug.DrugService.SyncFromFDA:output_type -> drug.SyncResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_drug_proto_init() }
func file_proto_drug_proto_init() {
	if File_proto_drug_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_drug_proto_rawDesc), len(file_proto_drug_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_drug_proto_goTypes,
		DependencyIndexes: file_proto_drug_proto_depIdxs,
		MessageInfos:      file_proto_drug_proto_msgTypes,
	}.Build()
	File_proto_drug_proto = out.File
	file_proto_drug_proto_goTypes = nil
	file_proto_drug_proto_depIdxs = nil
}
